workspace = { members = [ "hello_macro", "hello_macro_derive"] }
[package]
name = "macrodiddly"
version = "0.1.0"
edition = "2021"

[dependencies]
hello_macro_derive = { path = "./hello_macro_derive" }
hello_macro = { path = "./hello_macro" }
